name: test

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Cache Dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: .github
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.github/install_base.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: .github/install_dependencies.sh

      - name: Install Original Khaiii
        run: .github/install_base.sh

      - name: Install Khaiii
        run: .github/install_libc_for_go.sh

      - name: Test
        run: |
          go mod init go-khaiii
          go mod tidy
          go test -race ./...
        env:
          CGO_LDFLAGS: -L${{ github.workspace }} -lkhaiiic
          CGO_CFLAGS: -I${{ github.workspace }}