name: test

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Cache Dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: .github
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('.github/install_base.sh') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: .github/install_dependencies.sh

      - name: Show go env
        run: go env

      - name: Install Original Khaiii
        run: .github/install_base.sh

      - name: Install Khaiii
        run: .github/install_libc_for_go.sh

      - name: Test
        run: |
          ls -al
          cp -pf ./libkhaiii*.* /usr/local/lib
          cp -pf khaiiic.h /usr/local/include
          export CGO_LDFLAGS="-L/usr/local/lib -lkhaiiic"
          go mod init github.com/AhaOfficial/go-khaiii
          go mod tidy
          go test -race ./...