name: test

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: ${{ github.workspace }}
          key: ${{ runner.os }}-${{ hashFiles('.github/install_base.sh') }}

      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: .github/install_base.sh

      - name: install khaiii
        run: .github/install.sh
