name: test

on:
  pull_request: {}
  push:
    branches:
      - for_linux

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
    
      - name: Install Dependencies
        run: .github/install_dependencies.sh

      - name: Show go env
        run: go env

      - name: Build Original Khaiii and Make C Libraries
        run: make

      - name: Install Libraries, Header files, and Resources
        run: make install

      - name: Test
        run: |
          export CGO_LDFLAGS="-L/usr/local/lib -lkhaiiic"
          go mod init github.com/AhaOfficial/go-khaiii
          go mod tidy
          go test

  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
    
      - name: Install Dependencies
        run: .github/install_dependencies.sh

      - name: Show go env
        run: go env

      - name: Build Original Khaiii and Make C Libraries
        run: make

      - name: Install Libraries, Header files, and Resources
        run: make install

      - name: Test
        run: |
          export CGO_LDFLAGS="-L/usr/local/lib -lkhaiiic"
          go mod init github.com/AhaOfficial/go-khaiii
          go mod tidy
          go test