name: test

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  macos:
    strategy:
      matrix:
        go:
          - "1.17"
      fail-fast: false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/khaiii
          key: ${{ runner.os }}-${{ hashFiles('.github/install.sh') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: install dependencies
        run: |
          brew install git cmake qt
      - name: install khaiii
        run: |
          .github/install.sh
      - name: test
        run: |
          go version
          go test -v -race ./...
